# Changing problem statement to finding first blood

In [140]:
import pandas as pd

In [141]:
try:
    df = pd.read_csv('./leaguedata/player_stats_5a_v2.csv')
except:
    df = pd.read_csv('https://dl.dropboxusercontent.com/s/hswx7dzi2rssy6v/player_stats_5a_v2.csv?dl=0')

/Users/macchan/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (61,62,63,64) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [142]:
df.shape

(158640, 102)

In [143]:
try:
    processed= pd.read_csv('./processed_data/processed_pregame.csv')
except:
    processed = pd.read_csv('https://dl.dropboxusercontent.com/s/e2v7odk9xizig0t/processed_pregame.csv?dl=0')
processed.drop(columns=['participantId', 'championId', 'spell1Id',
       'spell2Id', 'perk0', 'perk1', 'perk2', 'perk3', 'perk4', 'perk5',
       'perkPrimaryStyle', 'perkSubStyle'],inplace=True)
processed.shape

(158640, 113)

In [144]:
processed.head()

,gameId,teamId,win,blue_1,blue_2,blue_3,blue_4,blue_5,red_6,red_7,...,blue_1_spell2Id,blue_2_spell2Id,blue_3_spell2Id,blue_4_spell2Id,blue_5_spell2Id,red_6_spell2Id,red_7_spell2Id,red_8_spell2Id,red_9_spell2Id,red_10_spell2Id
0,0,blue,red,Rek'Sai,Azir,Kennen,Miss Fortune,Yuumi,Thresh,Ekko,...,Smite,Flash,Teleport,Flash,Exhaust,Ignite,Smite,Heal,Flash,Flash
1,0,blue,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0,blue,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0,blue,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0,blue,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [145]:
tempdict = {}
for i in range(len(df['gameId'].value_counts())):
    temp = df[df['gameId']==i]
    switch = False
    for j in range(len(temp)):
        if temp['firstBloodKill'].iloc[j]:
            tempdict[i]=temp['teamId'].iloc[j]
            switch=True
        if switch==False:
            tempdict[i]=None

In [146]:
processed['gameId'].map(tempdict).value_counts()

blue    81420
red     77220
Name: gameId, dtype: int64

In [147]:
processed['firstblood']=processed['gameId'].map(tempdict)
processed.drop(columns=['gameId','teamId','win'],inplace=True)
processed.dropna(inplace=True)

In [148]:
processed.head()

,blue_1,blue_2,blue_3,blue_4,blue_5,red_6,red_7,red_8,red_9,red_10,...,blue_2_spell2Id,blue_3_spell2Id,blue_4_spell2Id,blue_5_spell2Id,red_6_spell2Id,red_7_spell2Id,red_8_spell2Id,red_9_spell2Id,red_10_spell2Id,firstblood
0,Rek'Sai,Azir,Kennen,Miss Fortune,Yuumi,Thresh,Ekko,Draven,Poppy,Yasuo,...,Flash,Teleport,Flash,Exhaust,Ignite,Smite,Heal,Flash,Flash,red
10,Pyke,Aphelios,Kled,Gragas,Bard,Gnar,Senna,Ekko,Draven,Volibear,...,Heal,Teleport,Smite,Flash,Flash,Ignite,Ignite,Heal,Smite,blue
20,Fiora,Dr. Mundo,Thresh,Jinx,Diana,Nami,Amumu,Kassadin,Ezreal,Mordekaiser,...,Flash,Ignite,Heal,Teleport,Exhaust,Flash,Teleport,Teleport,Flash,red
30,Blitzcrank,Ornn,Miss Fortune,Pyke,Kha'Zix,Elise,Thresh,Ekko,Draven,Fiora,...,Flash,Heal,Ignite,Flash,Smite,Ignite,Ignite,Heal,Teleport,red
40,Olaf,Kennen,Ornn,Miss Fortune,Thresh,Nunu & Willump,Ekko,Draven,Blitzcrank,Sona,...,Ignite,Flash,Heal,Ignite,Smite,Ignite,Heal,Ignite,Flash,red

In [150]:
processed = pd.get_dummies(processed).drop(columns='firstblood_red')
processed.to_csv('./model_data/model_data_fb.csv',index=False)